runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:vEJbGJcBilIptsIYC2qyLT8pap6Jx8cJcElrp8AlH+E=
    APP_NAME: MT4-history
    DB_CONNECTION: mysql
    DB_HOST: mysql
    DB_PORT: 3306
    DB_DATABASE: mt4_data
    DB_USERNAME: mt4_user
    DB_PASSWORD: mt4_pass
    LOGIN_FTP: b7_32978788
    MP_FTP: Spectre2014

    LOG_LEVEL: debug
