version: "3"
services:
  web:
    build: .
    depends_on:
      - mysql
    ports:
      - "9080:80"
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: adminer:4.8.1
    depends_on:
      - mysql
    ports:
      - "9081:8080"
